version: '3.8'

services:
  web:
    build: .
    command: sh entrypoin.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/numb_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=numb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: